version: "3.8"
services:
  cinema-home-client-server:
    build:
      context: ./cinema-home-client-server
      dockerfile: cinema-home-client-server.Dockerfile
    image: cinema-home-client-server:0.1-SNAPSHOT
    container_name: cinema-home-client-server
    environment:
      - NCORE_USERNAME=${NCORE_USERNAME}
      - NCORE_PASSWORD=${NCORE_PASSWORD}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - FANART_API_KEY=${FANART_API_KEY}
    ports:
      - "8080:8080"