version: "3.8"
services:
  cinema-home-client-server:
    build:
      context: ./cinema-home-client-server
      dockerfile: cinema-home-client-server.Dockerfile
    image: cinema-home-client-server:0.1-SNAPSHOT
    container_name: cinema-home-client-server
    environment:
      - NCORE_USERNAME=${NCORE_USERNAME}
      - NCORE_PASSWORD=${NCORE_PASSWORD}
      - TMDB_API_KEY=${TMDB_API_KEY}
      - FANART_API_KEY=${FANART_API_KEY}
      - TRANSMISSION_URL=http://cinema-home-transmission:9091/transmission/rpc
      - TRANSMISSION_USERNAME=${TRANSMISSION_USERNAME}
      - TRANSMISSION_PASSWORD=${TRANSMISSION_PASSWORD}
    ports:
      - "8080:8080"
    restart: unless-stopped
  cinema-home-transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: cinema-home-transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - USER=${TRANSMISSION_USERNAME}
      - PASS=${TRANSMISSION_PASSWORD}
    volumes:
      - ${TRANSMISSION_HOME}/config:/config
      - ${TRANSMISSION_HOME}/downloads:/downloads
      - ${TRANSMISSION_HOME}/watch:/watch
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    restart: unless-stopped