name: PUSH

on:
  push:
  pull_request:
  schedule:
    - cron:  '00 12 * * *'

jobs:
  test-client-server:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    name: OS-${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    - run: mvn clean verify --file cinema-home-client-server/pom.xml
